# Generated by Django 6.0 on 2025-12-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
