# Generated by Django 6.0 on 2025-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_wishlist_customer_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
