# Generated by Django 6.0 on 2025-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_farmerprofile_rating_alter_farmerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_detail/'),
        ),
    ]
