# Generated by Django 6.0 on 2025-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
