# Generated by Django 6.0 on 2025-12-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comemnt',
            new_name='comment',
        ),
    ]
